apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-dev
  namespace: development

spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/run/desktop/mnt/host/c/Users/gruby/technologie/projekt/development/mongo-volume-data-dev'
  claimRef:
    name: pvc-mongo
    namespace: development
