apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  namespace: deployment

spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/run/desktop/mnt/host/c/Users/gruby/technologie/projekt/deployment/mongo-volume-data'
  claimRef:
    name: pvc-mongo
    namespace: deployment
