apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: deployment

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: pv-mongo
  resources:
    requests:
      storage: 20Mi
